//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace AppMC.SR_CE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MigraCarnetdeExtrajeriaSoap11Binding", Namespace="http://ws.consulta.usuarios.migraciones.gob.pe/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(consulta))]
    public partial class MigraCarnetdeExtrajeria : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultarDocumentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MigraCarnetdeExtrajeria() {
            this.Url = global::AppMC.Properties.Settings.Default.AppMC_SR_CE_MigraCarnetdeExtrajeria;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarDocumentoCompletedEventHandler consultarDocumentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("consultarDocumento", RequestNamespace="http://ws.consulta.usuarios.migraciones.gob.pe/", ResponseNamespace="http://ws.consulta.usuarios.migraciones.gob.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public respuestaBean consultarDocumento([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] solicitudBean solicitud) {
            object[] results = this.Invoke("consultarDocumento", new object[] {
                        solicitud});
            return ((respuestaBean)(results[0]));
        }
        
        /// <remarks/>
        public void consultarDocumentoAsync(solicitudBean solicitud) {
            this.consultarDocumentoAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void consultarDocumentoAsync(solicitudBean solicitud, object userState) {
            if ((this.consultarDocumentoOperationCompleted == null)) {
                this.consultarDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarDocumentoOperationCompleted);
            }
            this.InvokeAsync("consultarDocumento", new object[] {
                        solicitud}, this.consultarDocumentoOperationCompleted, userState);
        }
        
        private void OnconsultarDocumentoOperationCompleted(object arg) {
            if ((this.consultarDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarDocumentoCompleted(this, new consultarDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consulta.usuarios.migraciones.gob.pe/")]
    public partial class solicitudBean : consulta {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudBean))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consulta.usuarios.migraciones.gob.pe/")]
    public abstract partial class consulta {
        
        private string strCodInstitucionField;
        
        private string strMacField;
        
        private string strNroIpField;
        
        private string strNumDocumentoField;
        
        private string strTipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strCodInstitucion {
            get {
                return this.strCodInstitucionField;
            }
            set {
                this.strCodInstitucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strMac {
            get {
                return this.strMacField;
            }
            set {
                this.strMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strNroIp {
            get {
                return this.strNroIpField;
            }
            set {
                this.strNroIpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strNumDocumento {
            get {
                return this.strNumDocumentoField;
            }
            set {
                this.strNumDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strTipoDocumento {
            get {
                return this.strTipoDocumentoField;
            }
            set {
                this.strTipoDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consulta.usuarios.migraciones.gob.pe/")]
    public partial class respuestaBean {
        
        private string strCalidadMigratoriaField;
        
        private string strNombresField;
        
        private string strNumRespuestaField;
        
        private string strPrimerApellidoField;
        
        private string strSegundoApellidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strCalidadMigratoria {
            get {
                return this.strCalidadMigratoriaField;
            }
            set {
                this.strCalidadMigratoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strNombres {
            get {
                return this.strNombresField;
            }
            set {
                this.strNombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strNumRespuesta {
            get {
                return this.strNumRespuestaField;
            }
            set {
                this.strNumRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strPrimerApellido {
            get {
                return this.strPrimerApellidoField;
            }
            set {
                this.strPrimerApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strSegundoApellido {
            get {
                return this.strSegundoApellidoField;
            }
            set {
                this.strSegundoApellidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void consultarDocumentoCompletedEventHandler(object sender, consultarDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuestaBean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuestaBean)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591