//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMC.SR_DNI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pe/gob/reniec/wsauth/WSDataVerification.wsdl", ConfigurationName="SR_DNI.WSDataVerificationPortType")]
    public interface WSDataVerificationPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSDataVerification) of message dataVerification0Request does not match the default value (http://pe/gob/reniec/wsauth/WSDataVerification.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="dataVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_DNI.dataVerification0Response dataVerification(AppMC.SR_DNI.dataVerification0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="dataVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_DNI.dataVerification0Response> dataVerificationAsync(AppMC.SR_DNI.dataVerification0Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSDataVerification) of message getDatavalidate1Request does not match the default value (http://pe/gob/reniec/wsauth/WSDataVerification.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="getDatavalidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_DNI.getDatavalidate1Response getDatavalidate(AppMC.SR_DNI.getDatavalidate1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDatavalidate", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_DNI.getDatavalidate1Response> getDatavalidateAsync(AppMC.SR_DNI.getDatavalidate1Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSDataVerification) of message getDatapersonal2Request does not match the default value (http://pe/gob/reniec/wsauth/WSDataVerification.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="getDatapersonal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_DNI.getDatapersonal2Response getDatapersonal(AppMC.SR_DNI.getDatapersonal2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDatapersonal", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_DNI.getDatapersonal2Response> getDatapersonalAsync(AppMC.SR_DNI.getDatapersonal2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataVerification", WrapperNamespace="WSDataVerification", IsWrapped=true)]
    public partial class dataVerification0Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlDocumento;
        
        public dataVerification0Request() {
        }
        
        public dataVerification0Request(string xmlDocumento) {
            this.xmlDocumento = xmlDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataVerificationResponse", WrapperNamespace="WSDataVerification", IsWrapped=true)]
    public partial class dataVerification0Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public dataVerification0Response() {
        }
        
        public dataVerification0Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatavalidate", WrapperNamespace="WSDataVerification", IsWrapped=true)]
    public partial class getDatavalidate1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlDocumento;
        
        public getDatavalidate1Request() {
        }
        
        public getDatavalidate1Request(string xmlDocumento) {
            this.xmlDocumento = xmlDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatavalidateResponse", WrapperNamespace="WSDataVerification", IsWrapped=true)]
    public partial class getDatavalidate1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getDatavalidate1Response() {
        }
        
        public getDatavalidate1Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatapersonal", WrapperNamespace="WSDataVerification", IsWrapped=true)]
    public partial class getDatapersonal2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlDocumento;
        
        public getDatapersonal2Request() {
        }
        
        public getDatapersonal2Request(string xmlDocumento) {
            this.xmlDocumento = xmlDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatapersonalResponse", WrapperNamespace="WSDataVerification", IsWrapped=true)]
    public partial class getDatapersonal2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getDatapersonal2Response() {
        }
        
        public getDatapersonal2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDataVerificationPortTypeChannel : AppMC.SR_DNI.WSDataVerificationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDataVerificationPortTypeClient : System.ServiceModel.ClientBase<AppMC.SR_DNI.WSDataVerificationPortType>, AppMC.SR_DNI.WSDataVerificationPortType {
        
        public WSDataVerificationPortTypeClient() {
        }
        
        public WSDataVerificationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDataVerificationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDataVerificationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDataVerificationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_DNI.dataVerification0Response AppMC.SR_DNI.WSDataVerificationPortType.dataVerification(AppMC.SR_DNI.dataVerification0Request request) {
            return base.Channel.dataVerification(request);
        }
        
        public string dataVerification(string xmlDocumento) {
            AppMC.SR_DNI.dataVerification0Request inValue = new AppMC.SR_DNI.dataVerification0Request();
            inValue.xmlDocumento = xmlDocumento;
            AppMC.SR_DNI.dataVerification0Response retVal = ((AppMC.SR_DNI.WSDataVerificationPortType)(this)).dataVerification(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_DNI.dataVerification0Response> AppMC.SR_DNI.WSDataVerificationPortType.dataVerificationAsync(AppMC.SR_DNI.dataVerification0Request request) {
            return base.Channel.dataVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_DNI.dataVerification0Response> dataVerificationAsync(string xmlDocumento) {
            AppMC.SR_DNI.dataVerification0Request inValue = new AppMC.SR_DNI.dataVerification0Request();
            inValue.xmlDocumento = xmlDocumento;
            return ((AppMC.SR_DNI.WSDataVerificationPortType)(this)).dataVerificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_DNI.getDatavalidate1Response AppMC.SR_DNI.WSDataVerificationPortType.getDatavalidate(AppMC.SR_DNI.getDatavalidate1Request request) {
            return base.Channel.getDatavalidate(request);
        }
        
        public string getDatavalidate(string xmlDocumento) {
            AppMC.SR_DNI.getDatavalidate1Request inValue = new AppMC.SR_DNI.getDatavalidate1Request();
            inValue.xmlDocumento = xmlDocumento;
            AppMC.SR_DNI.getDatavalidate1Response retVal = ((AppMC.SR_DNI.WSDataVerificationPortType)(this)).getDatavalidate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_DNI.getDatavalidate1Response> AppMC.SR_DNI.WSDataVerificationPortType.getDatavalidateAsync(AppMC.SR_DNI.getDatavalidate1Request request) {
            return base.Channel.getDatavalidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_DNI.getDatavalidate1Response> getDatavalidateAsync(string xmlDocumento) {
            AppMC.SR_DNI.getDatavalidate1Request inValue = new AppMC.SR_DNI.getDatavalidate1Request();
            inValue.xmlDocumento = xmlDocumento;
            return ((AppMC.SR_DNI.WSDataVerificationPortType)(this)).getDatavalidateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_DNI.getDatapersonal2Response AppMC.SR_DNI.WSDataVerificationPortType.getDatapersonal(AppMC.SR_DNI.getDatapersonal2Request request) {
            return base.Channel.getDatapersonal(request);
        }
        
        public string getDatapersonal(string xmlDocumento) {
            AppMC.SR_DNI.getDatapersonal2Request inValue = new AppMC.SR_DNI.getDatapersonal2Request();
            inValue.xmlDocumento = xmlDocumento;
            AppMC.SR_DNI.getDatapersonal2Response retVal = ((AppMC.SR_DNI.WSDataVerificationPortType)(this)).getDatapersonal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_DNI.getDatapersonal2Response> AppMC.SR_DNI.WSDataVerificationPortType.getDatapersonalAsync(AppMC.SR_DNI.getDatapersonal2Request request) {
            return base.Channel.getDatapersonalAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_DNI.getDatapersonal2Response> getDatapersonalAsync(string xmlDocumento) {
            AppMC.SR_DNI.getDatapersonal2Request inValue = new AppMC.SR_DNI.getDatapersonal2Request();
            inValue.xmlDocumento = xmlDocumento;
            return ((AppMC.SR_DNI.WSDataVerificationPortType)(this)).getDatapersonalAsync(inValue);
        }
    }
}
