//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMC.SR_AUT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pe/gob/reniec/wsauth/WSAuthentication.wsdl", ConfigurationName="SR_AUT.WSAuthenticationPortType")]
    public interface WSAuthenticationPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSAuthentication) of message getDTD0Request does not match the default value (http://pe/gob/reniec/wsauth/WSAuthentication.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="getDTD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_AUT.getDTD0Response getDTD(AppMC.SR_AUT.getDTD0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDTD", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_AUT.getDTD0Response> getDTDAsync(AppMC.SR_AUT.getDTD0Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSAuthentication) of message getSecureCode1Request does not match the default value (http://pe/gob/reniec/wsauth/WSAuthentication.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="getSecureCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_AUT.getSecureCode1Response getSecureCode(AppMC.SR_AUT.getSecureCode1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSecureCode", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_AUT.getSecureCode1Response> getSecureCodeAsync(AppMC.SR_AUT.getSecureCode1Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSAuthentication) of message registerUser2Request does not match the default value (http://pe/gob/reniec/wsauth/WSAuthentication.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="registerUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_AUT.registerUser2Response registerUser(AppMC.SR_AUT.registerUser2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="registerUser", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_AUT.registerUser2Response> registerUserAsync(AppMC.SR_AUT.registerUser2Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSAuthentication) of message loginValidation3Request does not match the default value (http://pe/gob/reniec/wsauth/WSAuthentication.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="loginValidation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_AUT.loginValidation3Response loginValidation(AppMC.SR_AUT.loginValidation3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="loginValidation", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_AUT.loginValidation3Response> loginValidationAsync(AppMC.SR_AUT.loginValidation3Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSAuthentication) of message changePin4Request does not match the default value (http://pe/gob/reniec/wsauth/WSAuthentication.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="changePin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_AUT.changePin4Response changePin(AppMC.SR_AUT.changePin4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="changePin", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_AUT.changePin4Response> changePinAsync(AppMC.SR_AUT.changePin4Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (WSAuthentication) of message getTicket5Request does not match the default value (http://pe/gob/reniec/wsauth/WSAuthentication.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="getTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppMC.SR_AUT.getTicket5Response getTicket(AppMC.SR_AUT.getTicket5Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMC.SR_AUT.getTicket5Response> getTicketAsync(AppMC.SR_AUT.getTicket5Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDTD", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class getDTD0Request {
        
        public getDTD0Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDTDResponse", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class getDTD0Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getDTD0Response() {
        }
        
        public getDTD0Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSecureCode", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class getSecureCode1Request {
        
        public getSecureCode1Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSecureCodeResponse", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class getSecureCode1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getSecureCode1Response() {
        }
        
        public getSecureCode1Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerUser", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class registerUser2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string paterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string materno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string fechanac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string email;
        
        public registerUser2Request() {
        }
        
        public registerUser2Request(string nombre, string paterno, string materno, string fechanac, string dni, string email) {
            this.nombre = nombre;
            this.paterno = paterno;
            this.materno = materno;
            this.fechanac = fechanac;
            this.dni = dni;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerUserResponse", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class registerUser2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public registerUser2Response() {
        }
        
        public registerUser2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginValidation", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class loginValidation3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string encriptCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string key;
        
        public loginValidation3Request() {
        }
        
        public loginValidation3Request(string userID, string encriptCode, string key) {
            this.userID = userID;
            this.encriptCode = encriptCode;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginValidationResponse", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class loginValidation3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public loginValidation3Response() {
        }
        
        public loginValidation3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePin", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class changePin4Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string encriptCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string key;
        
        public changePin4Request() {
        }
        
        public changePin4Request(string userID, string encriptCode, string key) {
            this.userID = userID;
            this.encriptCode = encriptCode;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePinResponse", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class changePin4Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public changePin4Response() {
        }
        
        public changePin4Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTicket", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class getTicket5Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public getTicket5Request() {
        }
        
        public getTicket5Request(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTicketResponse", WrapperNamespace="WSAuthentication", IsWrapped=true)]
    public partial class getTicket5Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getTicket5Response() {
        }
        
        public getTicket5Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAuthenticationPortTypeChannel : AppMC.SR_AUT.WSAuthenticationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAuthenticationPortTypeClient : System.ServiceModel.ClientBase<AppMC.SR_AUT.WSAuthenticationPortType>, AppMC.SR_AUT.WSAuthenticationPortType {
        
        public WSAuthenticationPortTypeClient() {
        }
        
        public WSAuthenticationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAuthenticationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAuthenticationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAuthenticationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_AUT.getDTD0Response AppMC.SR_AUT.WSAuthenticationPortType.getDTD(AppMC.SR_AUT.getDTD0Request request) {
            return base.Channel.getDTD(request);
        }
        
        public string getDTD() {
            AppMC.SR_AUT.getDTD0Request inValue = new AppMC.SR_AUT.getDTD0Request();
            AppMC.SR_AUT.getDTD0Response retVal = ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).getDTD(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_AUT.getDTD0Response> AppMC.SR_AUT.WSAuthenticationPortType.getDTDAsync(AppMC.SR_AUT.getDTD0Request request) {
            return base.Channel.getDTDAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_AUT.getDTD0Response> getDTDAsync() {
            AppMC.SR_AUT.getDTD0Request inValue = new AppMC.SR_AUT.getDTD0Request();
            return ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).getDTDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_AUT.getSecureCode1Response AppMC.SR_AUT.WSAuthenticationPortType.getSecureCode(AppMC.SR_AUT.getSecureCode1Request request) {
            return base.Channel.getSecureCode(request);
        }
        
        public string getSecureCode() {
            AppMC.SR_AUT.getSecureCode1Request inValue = new AppMC.SR_AUT.getSecureCode1Request();
            AppMC.SR_AUT.getSecureCode1Response retVal = ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).getSecureCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_AUT.getSecureCode1Response> AppMC.SR_AUT.WSAuthenticationPortType.getSecureCodeAsync(AppMC.SR_AUT.getSecureCode1Request request) {
            return base.Channel.getSecureCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_AUT.getSecureCode1Response> getSecureCodeAsync() {
            AppMC.SR_AUT.getSecureCode1Request inValue = new AppMC.SR_AUT.getSecureCode1Request();
            return ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).getSecureCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_AUT.registerUser2Response AppMC.SR_AUT.WSAuthenticationPortType.registerUser(AppMC.SR_AUT.registerUser2Request request) {
            return base.Channel.registerUser(request);
        }
        
        public string registerUser(string nombre, string paterno, string materno, string fechanac, string dni, string email) {
            AppMC.SR_AUT.registerUser2Request inValue = new AppMC.SR_AUT.registerUser2Request();
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.fechanac = fechanac;
            inValue.dni = dni;
            inValue.email = email;
            AppMC.SR_AUT.registerUser2Response retVal = ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).registerUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_AUT.registerUser2Response> AppMC.SR_AUT.WSAuthenticationPortType.registerUserAsync(AppMC.SR_AUT.registerUser2Request request) {
            return base.Channel.registerUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_AUT.registerUser2Response> registerUserAsync(string nombre, string paterno, string materno, string fechanac, string dni, string email) {
            AppMC.SR_AUT.registerUser2Request inValue = new AppMC.SR_AUT.registerUser2Request();
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.fechanac = fechanac;
            inValue.dni = dni;
            inValue.email = email;
            return ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).registerUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_AUT.loginValidation3Response AppMC.SR_AUT.WSAuthenticationPortType.loginValidation(AppMC.SR_AUT.loginValidation3Request request) {
            return base.Channel.loginValidation(request);
        }
        
        public string loginValidation(string userID, string encriptCode, string key) {
            AppMC.SR_AUT.loginValidation3Request inValue = new AppMC.SR_AUT.loginValidation3Request();
            inValue.userID = userID;
            inValue.encriptCode = encriptCode;
            inValue.key = key;
            AppMC.SR_AUT.loginValidation3Response retVal = ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).loginValidation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_AUT.loginValidation3Response> AppMC.SR_AUT.WSAuthenticationPortType.loginValidationAsync(AppMC.SR_AUT.loginValidation3Request request) {
            return base.Channel.loginValidationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_AUT.loginValidation3Response> loginValidationAsync(string userID, string encriptCode, string key) {
            AppMC.SR_AUT.loginValidation3Request inValue = new AppMC.SR_AUT.loginValidation3Request();
            inValue.userID = userID;
            inValue.encriptCode = encriptCode;
            inValue.key = key;
            return ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).loginValidationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_AUT.changePin4Response AppMC.SR_AUT.WSAuthenticationPortType.changePin(AppMC.SR_AUT.changePin4Request request) {
            return base.Channel.changePin(request);
        }
        
        public string changePin(string userID, string encriptCode, string key) {
            AppMC.SR_AUT.changePin4Request inValue = new AppMC.SR_AUT.changePin4Request();
            inValue.userID = userID;
            inValue.encriptCode = encriptCode;
            inValue.key = key;
            AppMC.SR_AUT.changePin4Response retVal = ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).changePin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_AUT.changePin4Response> AppMC.SR_AUT.WSAuthenticationPortType.changePinAsync(AppMC.SR_AUT.changePin4Request request) {
            return base.Channel.changePinAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_AUT.changePin4Response> changePinAsync(string userID, string encriptCode, string key) {
            AppMC.SR_AUT.changePin4Request inValue = new AppMC.SR_AUT.changePin4Request();
            inValue.userID = userID;
            inValue.encriptCode = encriptCode;
            inValue.key = key;
            return ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).changePinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMC.SR_AUT.getTicket5Response AppMC.SR_AUT.WSAuthenticationPortType.getTicket(AppMC.SR_AUT.getTicket5Request request) {
            return base.Channel.getTicket(request);
        }
        
        public string getTicket(string user, string password) {
            AppMC.SR_AUT.getTicket5Request inValue = new AppMC.SR_AUT.getTicket5Request();
            inValue.user = user;
            inValue.password = password;
            AppMC.SR_AUT.getTicket5Response retVal = ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).getTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMC.SR_AUT.getTicket5Response> AppMC.SR_AUT.WSAuthenticationPortType.getTicketAsync(AppMC.SR_AUT.getTicket5Request request) {
            return base.Channel.getTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMC.SR_AUT.getTicket5Response> getTicketAsync(string user, string password) {
            AppMC.SR_AUT.getTicket5Request inValue = new AppMC.SR_AUT.getTicket5Request();
            inValue.user = user;
            inValue.password = password;
            return ((AppMC.SR_AUT.WSAuthenticationPortType)(this)).getTicketAsync(inValue);
        }
    }
}
